### ISSUE TITLE
TODO for SSD Shell

### ISSUE THREAD

**Issue by ihansam** [demianmedich/SSD#20]
- [x] Shell -> SsdController, ReadResultAccessor -> ResultReader로 이름 변경
- [x] SsdShell 구현
- [x] TestApp 구현 (SsdController와 SsdShell에 직접 확장)
- [x] SSD core 물려서 기본 동작 확인
- [x] SsdShell 이것저것 input 넣어보며 예외 동작 확인
  - [x] int() 쓰는 부분에서 깨질 수 있음
- [ ] ResultReader 예외 처리
- [x] SsdController 리팩토링
- [ ] SsdController Test Case 추가
